// GENERATED by .design-sync/gen-entry.mjs — do not edit.
// Design-sync bundle entry: re-exports the components pinned in
// .design-sync/config.json > componentSrcMap. Not part of the app.

// process polyfill: components read process.env.NEXT_PUBLIC_MAPBOX_TOKEN
// (AddressAutocomplete, geocode, MapCanvas). esbuild only defines NODE_ENV, so a
// bare process.env.X read throws "process is not defined" in the browser. An empty
// env makes token-gated features degrade gracefully (AddressAutocomplete falls back
// to a plain text input) — the correct, network-free render for a static preview.
// Reads happen inside render, so setting this at entry-eval is early enough.
;(globalThis as unknown as { process?: { env: Record<string, string> } }).process ??= { env: { NODE_ENV: 'development' } }

export { AddressAutocomplete } from "@/features/demo/ui/inputs/AddressAutocomplete"
export { ArrivalDepartureScreen } from "@/features/demo/ui/screens/ArrivalDepartureScreen"
export { Banner } from "@/features/demo/ui/controls/Banner"
export { Calendar } from "@/features/demo/ui/inputs/Calendar"
export { CamerasScreen } from "@/features/demo/ui/screens/CamerasScreen"
export { CasesScreen } from "@/features/demo/ui/screens/CasesScreen"
export { CentredDialog } from "@/features/demo/ui/controls/CentredDialog"
export { CompletionScreen } from "@/features/demo/ui/screens/CompletionScreen"
export { DashboardScreen } from "@/features/demo/ui/screens/DashboardScreen"
export { DateField } from "@/features/demo/ui/inputs/DateField"
export { DateTimeField } from "@/features/demo/ui/inputs/DateTimeField"
export { Dropdown } from "@/features/demo/ui/inputs/Dropdown"
export { DvrInfoScreen } from "@/features/demo/ui/screens/DvrInfoScreen"
export { ExitDialog } from "@/features/demo/ui/controls/ExitDialog"
export { ExploreChecklist } from "@/features/demo/ui/controls/ExploreChecklist"
export { ExportInfoScreen } from "@/features/demo/ui/screens/ExportInfoScreen"
export { ExtractedScopeScreen } from "@/features/demo/ui/screens/ExtractedScopeScreen"
export { ImportModal } from "@/features/demo/ui/screens/ImportModal"
export { MapFiltersSheet } from "@/features/demo/ui/screens/map/MapFiltersSheet"
export { ModalShell } from "@/features/demo/ui/screens/_shared"
export { NewCaseModal } from "@/features/demo/ui/screens/NewCaseModal"
export { NewLocationModal } from "@/features/demo/ui/screens/NewLocationModal"
export { NotesScreen } from "@/features/demo/ui/screens/NotesScreen"
export { OcrCaptureScreen } from "@/features/demo/ui/screens/OcrCaptureScreen"
export { OverlayHeader } from "@/features/demo/ui/chrome/OverlayHeader"
export { PdfPreview } from "@/features/demo/ui/chrome/PdfPreview"
export { PickerSheet } from "@/features/demo/ui/inputs/PickerSheet"
export { RequestedScopeScreen } from "@/features/demo/ui/screens/RequestedScopeScreen"
export { SplashScreen } from "@/features/demo/ui/screens/SplashScreen"
export { SubmissionScreen } from "@/features/demo/ui/screens/SubmissionScreen"
export { SyncStatusCard } from "@/features/demo/ui/screens/SyncStatusCard"
export { TabBar } from "@/features/demo/ui/controls/TabBar"
export { TimeField } from "@/features/demo/ui/inputs/TimeField"
export { TimeOffsetScreen } from "@/features/demo/ui/screens/TimeOffsetScreen"
export { TimeWheel } from "@/features/demo/ui/inputs/TimeWheel"
export { TypewriterText } from "@/features/demo/ui/primitives/TypewriterText"
export { WizardDrawer } from "@/features/demo/ui/controls/WizardDrawer"
