// One-shot vendoring of the Case File type stack's OFL webfonts.
//
// Why this exists: the app gets Inter / Share Tech Mono / JetBrains Mono from
// `next/font/google`, which self-hosts them at BUILD time inside Next. The
// design-sync bundle has no Next compiler, so those families would resolve to
// nothing and every design would render in a fallback. We vendor the woff2s
// once and commit them — the build stays deterministic and offline.
//
// NOT part of cfg.buildCmd. Run by hand only when the type stack changes:
//   node .design-sync/fetch-fonts.mjs
//
// Licence: Inter, Share Tech Mono and JetBrains Mono are all SIL OFL 1.1,
// which permits redistribution. Nacelle is already vendored in public/fonts/.

import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = join(HERE, 'fonts')

// A modern UA is required — with an old/absent one Google serves legacy ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const FAMILIES = [
  { spec: 'Inter:wght@400;600;700', slug: 'inter' },
  { spec: 'Share+Tech+Mono', slug: 'share-tech-mono' },
  { spec: 'JetBrains+Mono:wght@400;700', slug: 'jetbrains-mono' },
]

// Google's css2 response annotates each @font-face with the subset it covers:
//   /* latin */
//   @font-face { ... }
// We keep latin only. Everything else is dead weight for this DS.
const KEEP_SUBSETS = new Set(['latin'])

function parseBlocks(css) {
  const out = []
  // Split on subset comments, keeping the label with the block that follows it.
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi
  let m
  while ((m = re.exec(css))) out.push({ subset: m[1].toLowerCase(), block: m[2] })
  return out
}

const field = (block, name) => block.match(new RegExp(`${name}:\\s*([^;]+);`, 'i'))?.[1].trim()

async function main() {
  await mkdir(OUT, { recursive: true })
  const rules = []
  let downloaded = 0

  for (const { spec, slug } of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${spec}&display=swap`
    const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => {
      if (!r.ok) throw new Error(`${spec}: css2 returned ${r.status}`)
      return r.text()
    })

    const blocks = parseBlocks(css).filter((b) => KEEP_SUBSETS.has(b.subset))
    if (!blocks.length) throw new Error(`${spec}: no latin @font-face found — did the css2 format change?`)

    // These families are VARIABLE fonts: css2 emits one @font-face per requested
    // weight, but every block points at the same file. Fetch each distinct URL
    // once and group the blocks by the bytes they resolve to, so a family ships
    // as a single woff2 with a weight RANGE rather than N identical copies.
    const byHash = new Map()
    for (const { block } of blocks) {
      const src = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1]
      if (!src) throw new Error(`${spec}: no woff2 url in block`)
      const style = field(block, 'font-style') ?? 'normal'

      const buf = Buffer.from(await fetch(src).then((r) => r.arrayBuffer()))
      const hash = createHash('sha256').update(buf).digest('hex').slice(0, 12)
      const key = `${hash}:${style}`

      const entry = byHash.get(key) ?? {
        buf,
        style,
        family: field(block, 'font-family')?.replace(/['"]/g, ''),
        range: field(block, 'unicode-range'),
        weights: [],
      }
      // A block's font-weight is either "400" or an explicit range "400 700".
      for (const w of (field(block, 'font-weight') ?? '400').split(/\s+/)) entry.weights.push(Number(w))
      byHash.set(key, entry)
    }

    for (const { buf, style, family, range, weights } of byHash.values()) {
      const lo = Math.min(...weights)
      const hi = Math.max(...weights)
      const weight = lo === hi ? `${lo}` : `${lo} ${hi}`
      const file = `${slug}${style === 'italic' ? '-italic' : ''}.woff2`

      await writeFile(join(OUT, file), buf)
      downloaded++
      console.log(`  ${file}  ${(buf.length / 1024).toFixed(1)}kb  (${family} ${weight} ${style})`)

      rules.push(
        [
          '@font-face {',
          `  font-family: '${family}';`,
          `  font-style: ${style};`,
          `  font-weight: ${weight};`,
          '  font-display: swap;',
          `  src: url('./fonts/${file}') format('woff2');`,
          range ? `  unicode-range: ${range};` : null,
          '}',
        ]
          .filter(Boolean)
          .join('\n'),
      )
    }
  }

  const header = [
    '/* GENERATED by .design-sync/fetch-fonts.mjs — do not hand-edit.',
    '   Latin-subset OFL webfonts for the Case File type stack, vendored so the',
    '   bundle needs no network and no Next compiler. Re-run the script to refresh. */',
    '',
  ].join('\n')

  await writeFile(join(HERE, 'fonts-google.css'), `${header}${rules.join('\n\n')}\n`)
  console.log(`\n${downloaded} woff2 → .design-sync/fonts/`)
  console.log(`${rules.length} @font-face → .design-sync/fonts-google.css`)
}

await main()
