#!/usr/bin/env node
// Generates .design-sync/ds-entry.ts — the design-sync bundle entry.
//
// Why this exists: features/demo/index.ts deliberately exports ONLY DemoExperience
// ("the public surface is intentionally tiny" — features/demo/CLAUDE.md). Bundling
// that barrel puts only DemoExperience on window.DVRDemoUI, so every preview card
// (which renders window.DVRDemoUI.<Name>) fails with "Element type is invalid".
//
// The converter's synth-entry fallback would `export * from` EVERY file under
// cfg.srcDir — that drags mapbox-gl (MapCanvas) and the Zustand store
// (DemoExperience) into the bundle. So instead we re-export exactly the components
// pinned in cfg.componentSrcMap: one source of truth, no drift.
//
// This does NOT widen the app's public API — the file is design-sync-only and is
// never imported by app code.
//
// Regenerate: node .design-sync/gen-entry.mjs   (run before package-build.mjs)

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, '..')

const cfg = JSON.parse(readFileSync(join(HERE, 'config.json'), 'utf8'))
const pinned = Object.entries(cfg.componentSrcMap ?? {}).filter(([, p]) => p !== null)

const lines = [
  '// GENERATED by .design-sync/gen-entry.mjs — do not edit.',
  '// Design-sync bundle entry: re-exports the components pinned in',
  '// .design-sync/config.json > componentSrcMap. Not part of the app.',
  '',
  '// process polyfill: components read process.env.NEXT_PUBLIC_MAPBOX_TOKEN',
  '// (AddressAutocomplete, geocode, MapCanvas). esbuild only defines NODE_ENV, so a',
  '// bare process.env.X read throws "process is not defined" in the browser. An empty',
  '// env makes token-gated features degrade gracefully (AddressAutocomplete falls back',
  '// to a plain text input) — the correct, network-free render for a static preview.',
  '// Reads happen inside render, so setting this at entry-eval is early enough.',
  ";(globalThis as unknown as { process?: { env: Record<string, string> } }).process ??= { env: { NODE_ENV: 'development' } }",
  '',
]

for (const [name, srcPath] of pinned.sort(([a], [b]) => a.localeCompare(b))) {
  // Import via the repo's own @/ alias so esbuild resolves through tsconfig paths,
  // exactly as app code does.
  const spec = '@/' + srcPath.replace(/\.tsx?$/, '')
  lines.push(`export { ${name} } from ${JSON.stringify(spec)}`)
}

const out = join(HERE, 'ds-entry.ts')
writeFileSync(out, lines.join('\n') + '\n')
console.log(`wrote ${relative(REPO, out)} — ${pinned.length} component re-exports`)
